#!/usr/bin/env python3

import sys
import os
import pathlib

ROOT_DIR = str(pathlib.Path(__file__).parent.parent)
sys.path.append(ROOT_DIR)
os.chdir(ROOT_DIR)

import click
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import random
import matplotlib.pyplot as plt
import json
import yaml
from datetime import datetime
from tqdm import tqdm

from rnd.model import RND



def save_config(config, output_dir):
    """Save training configuration."""
    config_path = os.path.join(output_dir, 'config.yaml')
    with open(config_path, 'w') as f:
        yaml.dump(config, f, default_flow_style=False)
    return config_path


def plot_loss_curve(losses, output_dir):
    """Plot training and validation loss curves."""
    plt.figure(figsize=(10, 6))
    
    epochs = range(1, len(losses) + 1)
    
    plt.subplot(1, 2, 1)
    plt.plot(epochs, losses, 'b-', label='Train Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Loss Curves')
    plt.legend()
    plt.grid(True)
    
    plt.subplot(1, 2, 2)
    plt.semilogy(epochs, losses, 'b-', label='Train Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss (log scale)')
    plt.title('Loss Curves (Log Scale)')
    plt.legend()
    plt.grid(True)
    
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'loss_curves.png'), dpi=150, bbox_inches='tight')
    plt.close()


@click.command()
@click.option('--task', '-t', default='can', help='Task of interest')
@click.option('--output-dir', '-o', default='data/rnd/', help='Output directory for saving models and logs')
@click.option('--hidden-dims', default='[512, 512]', help='Hidden dimensions as list')
@click.option('--output-dim', default=256, help='Output dimension for RND networks')
@click.option('--batch-size', '-b', default=64, help='Batch size for training')
@click.option('--num-epochs', '-e', default=200, help='Number of training epochs')
@click.option('--learning-rate', '-lr', default=1e-4, help='Learning rate')
@click.option('--weight-decay', default=1e-4, help='Weight decay for optimizer')
@click.option('--num-workers', '-w', default=4, help='Number of workers for data loading')
@click.option('--device', '-d', default='cuda:0', help='Device to use for training')
@click.option('--seed', default=42, help='Random seed')
@click.option('--save-every', default=20, help='Save checkpoint every N epochs')
def main(
        task,
        output_dir,
        hidden_dims,
        output_dim,
        batch_size,
        num_epochs,
        learning_rate,
        weight_decay,
        num_workers,
        device,
        seed,
        save_every):
    """
    Train Random Network Distillation (RND) on observation embeddings.
    
    This script loads observation embeddings generated by a flow_match policy
    and trains an RND model to learn an intrinsic reward function.
    """
    
    # Set random seeds
    torch.backends.cudnn.deterministic = True
    random.seed(seed)
    torch.manual_seed(seed)
    np.random.seed(seed)
    
    # Parse hidden dimensions
    try:
        hidden_dims = eval(hidden_dims)
        if not isinstance(hidden_dims, list):
            raise ValueError("hidden_dims must be a list")
    except:
        raise ValueError(f"Invalid hidden_dims format: {hidden_dims}")
    
    # Create output directory
    now = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_dir = str(pathlib.Path(output_dir) / task / now)
    os.makedirs(output_dir, exist_ok=True)
    
    # 1.1 load observation embeddings
    data_path = f'data/rnd/{task}_image_20_flow_obs_emb.pt'
    payload = torch.load(data_path)
    obs_emb = payload['obs_emb']  # Shape: (N, Do)
    policy = payload['checkpoint']
    
    # 1.2 Create datasets and dataloader
    dataset =  TensorDataset(obs_emb)
    train_loader = DataLoader(
        dataset, 
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True
    )
    
    # 2. Create model
    input_dim = obs_emb.shape[1]  # Input dimension is the embedding size
    model = RND(
        input_dim=input_dim,
        hidden_dims=hidden_dims,
        output_dim=output_dim
    )
    model.to(device)
    total_params = sum(p.numel() for p in model.parameters()) / 1_000
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad) / 1_000
    print(f"Total parameters: {total_params:,} K")
    print(f"Trainable parameters: {trainable_params:,} K")
    
    # 3. Create optimizer and loss function
    optimizer = optim.AdamW(
        model.predictor.parameters(),  # Only train predictor, target is frozen
        lr=learning_rate,
        weight_decay=weight_decay
    )
    
    # Training configuration
    config = {
        'data_path': data_path,
        'input_dim': input_dim,
        'hidden_dims': hidden_dims,
        'output_dim': output_dim,
        'batch_size': batch_size,
        'num_epochs': num_epochs,
        'learning_rate': learning_rate,
        'weight_decay': weight_decay,
        'device': device,
        'seed': seed,
        'total_samples': len(obs_emb),
        'train_samples': len(dataset),
        'timestamp': now,
        'policy': policy,
    }
    
    # Save config
    config_path = save_config(config, output_dir)
    print(f"Config saved to: {config_path}")
    
    # Training loop
    losses = []
    
    for epoch in range(1, num_epochs + 1):
        # Training
        model.train()
        train_loss = 0.0
        
        with tqdm(train_loader, desc=f"Epoch {epoch}/{num_epochs} [Train]",
                leave=False) as tepoch:
            for batch_idx, (obs_emb,) in enumerate(tepoch):
                obs_emb = obs_emb.to(device)

                optimizer.zero_grad()            
                rnd_distances = model(obs_emb)  # (B,)
                loss = rnd_distances.mean()

                loss.backward()
                optimizer.step()

                train_loss += loss.item()
                tepoch.set_postfix({'loss': loss.item()})

        train_loss /= len(train_loader)
        losses.append(train_loss)

        # Save checkpoint
        if epoch % save_every == 0:
            torch.save({
                'epoch': epoch,
                'model': model.state_dict(),
                'optimizer': optimizer.state_dict(),
                'losses': losses,
                'config': config,
            }, os.path.join(output_dir, f'{task}_flow_epoch={epoch}.ckpt'))

    # Plot loss curves
    plot_loss_curve(losses, output_dir)


if __name__ == "__main__":
    main()