defaults:
  - _self_
  - online_task: can_image_abs

name: train_online_noise_robomimic_workspace
_target_: diffusion_policy.workspace.train_online_noise_robomimic_workspace.TrainOnlineNoiseRobomimicWorkspace

task_name: ${online_task.name}
shape_meta: ${online_task.shape_meta}
exp_name: "default"

horizon: 16
n_obs_steps: 1
n_action_steps: 4
n_latency_steps: 0

noise_policy:
  _target_: diffusion_policy.policy.noise_policy.NoisePolicy
  obs_dim: ???
  action_dim: ???
  hidden_dim: 256
  log_std_min: -2.0
  log_std_max: 2.0
  gamma: ${eval:"round(0.99**${n_action_steps}, 2)"}
  tau: 0.005
  init_alpha: 0.01
  auto_alpha: True
  num_qs: 2
  num_subset: 2

training:
  device: "cuda:0"
  seed: 42
  debug: False
  # optimization
  batch_size: 256
  policy_lr: 1e-4
  q_lr: 3e-4
  learning_start: 1000
  # lr_scheduler: cosine
  # lr_warmup_steps: 100
  max_grad_norm: 50.0
  policy_freq: 2
  target_freq: 2
  training_freq: 1000
  utd: 1.0
  n_envs: ${online_task.n_envs}
  # residue progress
  noise_scale: 1.5
  bootstrap_at_done: never  # never, always, truncated
  # training loop control in steps
  q_pretrain_steps: 0
  num_steps: 1000000
  buffer_size: 1000000
  log_every: 1000
  eval_every: 50000
  checkpoint_every: 100000
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: online_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}