defaults:
  - _self_
  - online_task: square_image_abs

name: train_online_vib_real_example_workspace
_target_: diffusion_policy.workspace.train_online_vib_real_example_workspace.TrainOnlineVibRealExampleWorkspace

task_name: ${online_task.name}
shape_meta: ${online_task.shape_meta}
exp_name: "default"

horizon: 16
n_obs_steps: 1
n_action_steps: 4 # 5 for transport, others 4
n_latency_steps: 0

res_policy:
  _target_: diffusion_policy.policy.latent_policy.ResiduePolicy
  obs_dim: ???
  z_dim: ???
  action_dim: ???
  actor_input_type: obs_sample
  hidden_dim: 256
  log_std_min: -10.0
  log_std_max: 2.0
  # gamma: ${eval:"round(0.997**${n_action_steps}, 3)"}  # for transport
  gamma: ${eval:"round(0.99**${n_action_steps}, 2)"}  # for can, square is enough
  tau: 0.005
  init_alpha: 0.01
  auto_alpha: True
  res_scale: ${training.res_scale}
  num_qs: 2
  num_subset: 2

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume_from: data/outputs/2026.01.07/10.29.09_train_online_vib_real_example_workspace_square_image
  # optimization
  batch_size: 256
  policy_lr: 1e-4
  q_lr: 3e-4
  learning_start: 2000  # 4k for transport, 2k for others
  # lr_scheduler: cosine
  # lr_warmup_steps: 100
  max_grad_norm: 50.0
  policy_freq: 2
  target_freq: 2
  training_freq: 4
  utd: 1.0
  n_envs: 1
  # residue progress
  res_scale: 0.2
  bootstrap_at_done: never  # never, always, truncated
  # training loop control in steps
  q_pretrain_steps: 0
  num_steps: 1000000
  buffer_size: 250000  # 500k for transport, 1M for others
  log_every: 1000
  eval_every: 50000
  checkpoint_every: 1000
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: online_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}