defaults:
  - _self_
  - online_task: wallet

name: train_online_vib_real_workspace
_target_: diffusion_policy.workspace.train_online_vib_real_workspace.TrainOnlineVibRealWorkspace

task_name: ${online_task.name}
shape_meta: ${online_task.shape_meta}
exp_name: "default"

horizon: 16
n_obs_steps: 1
n_action_steps: 16
n_latency_steps: 0
num_inference_steps: 10

res_policy:
  _target_: diffusion_policy.policy.latent_policy.ResiduePolicy
  obs_dim: ???
  z_dim: ???
  action_dim: ???
  actor_input_type: obs_sample
  hidden_dim: 256
  log_std_min: -8.0
  log_std_max: 2.0
  gamma: ${eval:"round(0.998**${n_action_steps}, 4)"}
  tau: 0.005
  init_alpha: 0.01
  auto_alpha: True
  res_scale: ${training.res_scale}
  num_qs: 10
  num_subset: 2

training:
  device: "cuda:0"
  seed: 0
  debug: False
  resume_from: null
  # optimization
  batch_size: 256
  policy_lr: 1e-4
  q_lr: 3e-4
  learning_start: 1000
  # lr_scheduler: cosine
  # lr_warmup_steps: 100
  max_grad_norm: 50.0
  policy_freq: 2
  target_freq: 2
  training_freq: 500
  utd: 5.0
  n_envs: 1
  # residue progress
  res_scale: 0.2
  bootstrap_at_done: never  # never, always, truncated
  # training loop control in steps
  q_pretrain_steps: 0
  num_steps: 50000
  buffer_size: 50000
  log_every: 50
  checkpoint_every: 200
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: real_online_debug
  resume: True
  mode: offline
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}