defaults:
  - _self_

name: train_on_policy_mujoco_workspace
_target_: diffusion_policy.workspace.train_on_policy_mujoco_workspace.TrainOnPolicyMujocoWorkspace

task_name: "Walker2d-v2"
exp_name: "default"

n_obs_steps: 1
n_action_steps: 1

res_policy:
  _target_: diffusion_policy.policy.residue_policy_ppo.ResiduePolicyPPO
  obs_dim: ???
  action_dim: ???
  log_std_max: 1.0
  log_std_min: -5.0
  actor_input: obs
  gamma: ${eval:"round(0.99**${n_action_steps}, 2)"}
  gae_lambda: 0.95
  clip_range: 0.2
  vf_coef: 0.5
  res_scale: ${training.res_scale}

training:
  device: "cuda:0"
  seed: 42
  debug: False
  # optimization
  n_epochs: 30
  batch_size: 128
  policy_lr: 1e-4  # 1e-4, 3e-4
  max_grad_norm: 0.5
  # lr_scheduler: cosine
  # lr_warmup_steps: 100
  n_envs: 16
  n_eval_trajs: 100
  n_eval_envs: 25
  # residue progress
  res_scale: 1.0
  # training loop control in steps
  num_steps: 1000000
  training_freq: 2048
  log_every: 2048
  eval_every: 51200
  checkpoint_every: 204800
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: online_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}