defaults:
  - train_flow_match_vib_unet_image_workspace
  - _self_

name: train_flow_match_vib_unet_image_ddp
_target_: diffusion_policy.workspace.train_flow_match_vib_unet_image_ddp_workspace.TrainFlowMatchVibUnetImageDDPWorkspace

dataloader:
  num_workers: 12

val_dataloader:
  num_workers: 4

training:
  mixed_precision: "no"
  ddp_find_unused_parameters: True
