name: adroit_door
task_name: door

shape_meta: &shape_meta
  obs:
    image:
      shape: [3, 84, 84]
      type: rgb
    agent_pos:
      shape: [24]
      type: low_dim
  action:
    shape: [28]

base_ckpt: "data/outputs/2025.12.09/18.14.34_train_flow_match_vib_unet_image_adroit_door/checkpoints/latest.ckpt"

# train
n_envs: 20

success_threshold: 50

# eval
env_runner:
  _target_: diffusion_policy.env_runner.adroit_runner.AdroitRunner
  eval_episodes: 50
  max_steps: 200
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  task_name: door
  tqdm_interval_sec: 1.0
  n_envs: 25
  test_start_seed: 10000
  render_device_id: ${eval:'int("${training.device}"[-1])'}