name: wallet

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    global:
      shape: [3, 120, 160]
      type: rgb
    wrist_0:
      shape: [3, 120, 160]
      type: rgb
    wrist_1:
      shape: [3, 120, 160]
      type: rgb
    qpos:
      shape: [16]
      type: low_dim
  action: 
    shape: [16]

task_name: &task_name wallet
dataset_path: /media/datahub-2/ydj/real/wallet/wallet.h5

dataset:
  _target_: diffusion_policy.dataset.wallet_dataset.WalletDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  use_cache: True
  seed: 0
  val_ratio: 0.02
  num_demo: 50
