defaults:
  - train_flow_match_unet_image_workspace
  - _self_

name: train_diffusion_image_accelerate
_target_: zprl.workspace.train_diffusion_image_accelerate_workspace.TrainDiffusionImageAccelerateWorkspace

dataloader:
  num_workers: 6

val_dataloader:
  num_workers: 2

training:
  resume: False
  gradient_accumulate_every: 1
  freeze_encoder: False
  mixed_precision: "no"
  ddp_find_unused_parameters: True
