defaults:
  - _self_
  - online_task: square_image_abs

name: train_online_robomimic_workspace
_target_: zprl.workspace.train_online_robomimic_workspace.TrainOnlineRobomimicWorkspace

task_name: ${online_task.name}
shape_meta: ${online_task.shape_meta}
exp_name: "default"

horizon: 16
n_obs_steps: 1
n_action_steps: 4 # 5 for transport, others 4
n_latency_steps: 0
single_gamma: 0.99  # single-step gamma; multi-step gamma for RL is computed from this
num_inference_steps: 2

res_policy:
  _target_: zprl.policy.td3_policy.TD3Policy
  obs_dim: ???
  action_dim: ???
  actor_input: obs_action
  hidden_dim: 256
  gamma: ${eval:"round(${single_gamma}**${n_action_steps}, 4)"}  # multi-step gamma for Bellman target
  tau: 0.005
  res_scale: ${training.res_scale}
  stddev_clip: 0.3
  num_qs: 10
  num_subset: 2

training:
  device: "cuda:0"
  seed: 42
  debug: False
  # optimization
  batch_size: 256
  policy_lr: 1e-4
  q_lr: 3e-4
  learning_start: 2000  # 4k for transport, 2k for others
  # lr_scheduler: cosine
  # lr_warmup_steps: 100
  max_grad_norm: 50.0
  policy_freq: 2
  target_freq: 2
  training_freq: 1000
  utd: 5.0
  # stddev schedule: linear decay from max to min over stddev_steps
  stddev_max: 0.1
  stddev_min: 0.1
  stddev_steps: 500000
  # residue progress
  res_scale: 0.05
  prog_explore: 50000
  bootstrap_at_done: never  # never, always, truncated
  # training loop control in steps
  preload_offline_data: True
  preload_shuffle: True
  q_pretrain_steps: 0
  num_steps: 250000
  buffer_size: 250000  # 500k for transport, 1M for others
  log_every: 1000
  eval_every: 150000
  checkpoint_every: 150000
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: online_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}