defaults:
  - train_flow_match_vib_unet_image_workspace
  - _self_

name: train_flow_match_vib_unet_image_accelerate
_target_: zprl.workspace.train_flow_match_vib_unet_image_accelerate_workspace.TrainFlowMatchVibUnetImageAccelerateWorkspace

dataloader:
  num_workers: 6

val_dataloader:
  num_workers: 2

training:
  mixed_precision: "no"
  ddp_find_unused_parameters: True
