defaults:
  - _self_
  - online_task: metaworld_box-close

name: train_online_vib_workspace
_target_: zprl.workspace.train_online_vib_workspace.TrainOnlineVibWorkspace

task_name: ${online_task.name}
shape_meta: ${online_task.shape_meta}
exp_name: "default"

horizon: 8
n_obs_steps: 1
n_action_steps: 2
n_latency_steps: 0
num_inference_steps: 5
single_gamma: 0.99  # single-step gamma; multi-step gamma for RL is computed from this

res_policy:
  _target_: zprl.policy.latent_policy.ResiduePolicy
  obs_dim: ???
  z_dim: ???
  action_dim: ???
  actor_input_type: obs_sample
  hidden_dim: 256
  log_std_min: -10.0
  log_std_max: 2.0
  gamma: ${eval:"round(${single_gamma}**${n_action_steps}, 2)"}  # multi-step gamma for Bellman target
  tau: 0.005
  init_alpha: 0.01 # 0.1 | 0.01
  auto_alpha: True
  res_scale: ${training.res_scale}
  num_qs: 2
  num_subset: 2

training:
  device: "cuda:0"
  seed: 42
  debug: False
  # optimization
  batch_size: 256
  policy_lr: 1e-4
  q_lr: 3e-4
  learning_start: 10000
  # lr_scheduler: cosine
  # lr_warmup_steps: 100
  max_grad_norm: 1.0
  policy_freq: 2
  target_freq: 1
  training_freq: 1000
  utd: 1.0
  n_envs: ${online_task.n_envs}
  # residue progress
  res_scale: 0.25  # TODO
  bootstrap_at_done: truncated  # never, truncated
  # training loop control in steps
  num_steps: 500000
  buffer_size: 500000
  log_every: 1000
  eval_every: 10000
  checkpoint_every: 100000
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: metaworld_online_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}