# -*- coding: utf-8 -*-
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json
from pathlib import Path

# =============================================================================
# 1. Helper function to retrieve eval data
# This part is the same as before.
# =============================================================================
def load_data(run_dir, expected_len):
    """
    Load eval data from run_dir/logs.json.txt
    """
    log_file = Path(run_dir) / 'logs.json.txt'
    if not log_file.is_file():
        print(f"Log file not found: {log_file}")
        return np.array([])

    scores = []
    with log_file.open('r') as f:
        for line in f:
            try:
                log_data = json.loads(line)
                if 'test/mean_score' in log_data:
                    scores.append(log_data['test/mean_score'])
            except json.JSONDecodeError:
                # Ignore malformed lines
                continue
    
    assert len(scores) == expected_len, \
        f"Run {run_dir} has {len(scores)} data points, expected {expected_len}"
    return np.array(scores)

# =============================================================================
# 2. Data Preparation using Pandas
# =============================================================================

# Data sources dictionary remains the same
data_sources = {
    'demo_env': [
        '2025.08.20/14.03.30_train_online_robomimic_workspace_square_image',
        '2025.08.20/10.48.21_train_online_robomimic_workspace_square_image',
        '2025.08.19/13.50.14_train_online_robomimic_workspace_square_image',
    ],
    'random_env': [
        '2025.08.20/14.02.36_train_online_robomimic_workspace_square_image',
        '2025.08.20/10.48.03_train_online_robomimic_workspace_square_image',
        '2025.08.19/13.57.35_train_online_robomimic_workspace_square_image',
    ],
    'pi-dec': [
        '2025.08.21/16.45.01_train_online_robomimic_workspace_square_image',
        '2025.08.21/16.45.16_train_online_robomimic_workspace_square_image',
        '2025.08.21/16.45.54_train_online_robomimic_workspace_square_image',
    ]
}

# --- Create a "long-form" DataFrame from all experimental data ---
## assume all runs shares the same train_step & eval_every, now 1M, 50K
EVAL_EVERY = 50_000
TOTAL_STEPS = 1_000_000
x_steps = np.arange(0, TOTAL_STEPS + 1, EVAL_EVERY) / float(TOTAL_STEPS)

all_data = []
for i, (name, dirs) in enumerate(data_sources.items()):
    for j, run_dir in enumerate(dirs):
        run_dir = 'data/outputs/' + run_dir
        y_values = load_data(run_dir, expected_len=len(x_steps))

        # Create a temporary DataFrame for this single run
        run_df = pd.DataFrame({
            'Steps': x_steps,
            'Performance': y_values,
            'Algorithm': name,
            'Run': j
        })
        all_data.append(run_df)


# Concatenate all run data into a single DataFrame
df = pd.concat(all_data, ignore_index=True)

# print(df.head()) # Uncomment to inspect the DataFrame

# =============================================================================
# 3. Plotting with Seaborn and Matplotlib
# =============================================================================

# --- Plotting Configuration ---
# Use the same color and marker schemes
palette = {
    'random_env': '#E63983',
    'demo_env': '#56B4E9',
    'pi-dec': "#59D171",
}
markers = {
    'random_env': 'o',
    'demo_env': 'v',
    'pi-dec': 's',
    'can_blue_triangle': '^',
    'can_blue_diamond': 'D',
    # backup: x, +, X, *
}

# --- Create Plot ---
sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(4.5, 3.5))

# --- Use seaborn.lineplot ---
# This single function handles grouping, aggregation (mean), and error bands (std dev).
sns.lineplot(
    data=df,
    x='Steps',
    y='Performance',
    hue='Algorithm',      # Color lines by algorithm
    style='Algorithm',    # Change markers by algorithm
    markers=markers,      # Dictionary mapping algorithms to markers
    palette=palette,      # Dictionary mapping algorithms to colors
    dashes=False,
    errorbar=('ci', 95),        # Show standard deviation as the error band
    ax=ax,
    linewidth=1.5,
)

# --- Customize Aesthetics (same as before) ---
# ax.set_title('can', fontsize=14)
ax.set_xlabel('Steps (x1M)', fontsize=12)
ax.set_ylabel('Success rate', fontsize=12)
ax.set_xlim(left=-0.05, right=1.05)
ax.set_ylim(bottom=-0.05, top=1.05)
ax.set_xticks([0.0, 0.25, 0.5, 0.75, 1.0])
ax.set_yticks([0.00, 0.25, 0.50, 0.75, 1.00])
ax.tick_params(axis='both', which='major', labelsize=11)
ax.yaxis.set_major_formatter('{x:.2f}')
ax.grid(True, which='major', linestyle='-', linewidth='0.5', color='lightgrey')

# Customize the legend generated by Seaborn
handles, labels = ax.get_legend_handles_labels()
ax.legend(handles=handles, labels=labels, fontsize=10)

plt.tight_layout()
fig.savefig('square.png', dpi=300, bbox_inches='tight')